
name: without cache

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: yarn
    - name: Validate cache
      run: yarn --immutable
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: yarn
    - run: yarn 
    - run: yarn tsc
    needs: install
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: yarn
    - run: yarn
    - run: yarn build
    needs: install
    