name: Node.js CI

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        cache: yarn
    - run: yarn
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        cache: yarn
    - run: yarn 
    - run: yarn tsc
    needs: install
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        cache: yarn
    - run: yarn
    - run: yarn build
    needs: install
    