
name: Node.js CI

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Validate cache
      env:
        # Use PnP and disable postinstall scripts as this just needs to
        # populate the cache for the other jobs
        YARN_NODE_LINKER: pnp
        YARN_ENABLE_SCRIPTS: false
      run: yarn --immutable
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn --frozen-lockfile 
    - run: yarn tsc
    needs: install
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
    needs: install
    